<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CrashBandicoot.Switch</RootNamespace>
    <AssemblyName>CrashBandicoot.Switch</AssemblyName>
    <PublishAot>false</PublishAot>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RecompOne.Runtime\RecompOne.Runtime.csproj" />
  </ItemGroup>
<ItemGroup>
  <Compile Include="sdl2-cs\src\**\*.cs" />
</ItemGroup>
</Project>
