<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- Runtime upstream to net10.0 — musi się zgadzać -->
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CrashBandicoot.Switch</RootNamespace>
    <AssemblyName>CrashBandicoot.Switch</AssemblyName>
    <PublishAot>false</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RecompOne.Runtime\RecompOne.Runtime.csproj" />
  </ItemGroup>
</Project>
